spring:
  application:
    name: order-service   # OR product-service (must be unique!)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka
